version: '3'

services:
  vietis_chatbot_api:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: vietis_chatbot_api
    container_name: vietis_chatbot_api
    depends_on:
      - vietis_chatbot_mysql
    volumes:
      - .:/src
    env_file:
      - ./.env
    ports:
      - "8083:8000"
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - vietis_chatbot_backend

  vietis_chatbot_mysql:
    image: mysql:8.0
    container_name: vietis_chatbot_mysql
    command: "--default-authentication-plugin=mysql_native_password"
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - vietis_chatbot_mysql_data:/var/lib/mysql
    networks:
      - vietis_chatbot_backend

networks:
  vietis_chatbot_backend:

volumes:
  vietis_chatbot_mysql_data:
  redis_data:
