# Generated by Django 4.2.3 on 2023-10-31 15:56

import apps.chat_bot.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('storage_vector_name', models.CharField(max_length=128)),
                ('vector_config_name', models.CharField(max_length=128)),
                ('prompt_message', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'bot',
            },
        ),
        migrations.CreateModel(
            name='CustomDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.chat_bot.models.pdf_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
            options={
                'db_table': 'custom_data_file',
            },
        ),
    ]
