# Generated by Django 4.2.3 on 2023-07-31 05:47

import apps.chat_bot.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('storage_vector_name', models.CharField(max_length=128)),
                ('vector_config_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'master_conversation',
            },
        ),
        migrations.CreateModel(
            name='CustomDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('file', models.FileField(upload_to=apps.chat_bot.models.pdf_directory_path)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot.masterconversation')),
            ],
            options={
                'db_table': 'custom_data_file',
            },
        ),
    ]
