# Generated by Django 4.2.3 on 2023-08-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterconversation',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='masterconversation',
            name='prompt_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
