# Generated by Django 4.2.3 on 2023-09-22 02:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0006_alter_customdatafile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdatafile',
            name='type',
            field=models.CharField(choices=[('1', 'Document'), ('2', 'Video Caption')], default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='masterconversation',
            name='refer_type',
            field=models.CharField(choices=[('1', 'Document Sources'), ('2', 'URL')], default=1, max_length=128),
        ),
        migrations.CreateModel(
            name='ReferUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=128, null=True, validators=[django.core.validators.URLValidator()])),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot.customdatafile')),
            ],
            options={
                'db_table': 'refer_url',
            },
        ),
    ]
